apps/invoices/urls.py
from django.conf.urls import url
from .views import CreateInvoice, DetailInvoice, EditInvoice, DeleteInvoice

urlpatterns = [
    url(r'^panel/invoices/nuevo/$', CreateInvoice.as_view(), name="nuevo"),
	url(r'^panel/invoices/(?P<pk>\d+)/$', DetailInvoice.as_view(), name="detalle"),
	url(r'^panel/invoices/editar/(?P<pk>\d+)/$', EditInvoice.as_view(), name="editar"),
	url(r'^panel/invoices/eliminar/(?P<pk>\d+)/$', DeleteInvoice.as_view(), name="eliminar"),

]

apps/main/urls.py
from django.conf.urls import url
from .views import Home

urlpatterns = [
	url(r'^$', Home.as_view(), name="home"),
]

apps/users/urls.py
from django.conf.urls import url
#para importar vista basadas en clases
from .views import LoginView, RegisterView
#para importa vistas basadas en funciones
from . import views

urlpatterns = [
    url(r'^ingresar/$', LoginView.as_view(), name="login"),
    url(r'^register/$', RegisterView.as_view(), name="register"),
    url(r'^salir/$', views.LogOut, name="logout"),
]

facturacion/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.main.urls', namespace="main")),
    url(r'^', include('apps.invoices.urls', namespace="invoice_app")),
    url(r'^', include('apps.users.urls', namespace="users")),
]

if settings.DEBUG :
	urlpatterns += [ 
		url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
	]

apps/invoices/models.py
#encoding:utf-8
from django.db import models

class Invoice(models.Model):
	date = models.DateField(auto_now_add=False)
	cliente = models.CharField(max_length=150)
	number = models.PositiveIntegerField(default=0, blank=True, null=True)
	total = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)

	def __unicode__(self):
		return "%d" %self.number

class InvoiceLine(models.Model):
	invoice = models.ForeignKey(Invoice)
	product = models.CharField(max_length=150)
	qty = models.PositiveIntegerField(default=0, blank=True, null=True)
	price_unit = total = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
	total = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)

	def __unicode__(self):
		return "Factura: %s - Detalle: %d" %(self.invoice.number,self.id)

apps/main/models.py
from django.db import models

# Create your models here.

apps/users/models.py
from django.db import models

# Create your models here.

apps/invoices/forms.py
from django import forms
from .models import Invoice

class InvoiceForm(forms.ModelForm):
	class Meta:
		model = Invoice
		fields = '__all__'

apps/users/forms.py
#encoding:utf-8
from django import forms
from django.contrib.auth.models import User

class UserLoginForm(forms.Form):

	username = forms.CharField(max_length=50,
					widget=forms.TextInput(attrs={
						'type' : 'text',
						'placeholder' : 'Ingrese un nombre de Usuario',
						}))
	password = forms.CharField(max_length=50,
					widget=forms.TextInput(attrs={
						'type' : 'password',
						'placeholder' : 'Ingrese una Contraseña'
						}))

	def clean(self):
		if not User.objects.filter(username = self.cleaned_data['username']):
			self.add_error('username', 'El nombre de usuario no existe')
		else:
			user = User.objects.get(username = self.cleaned_data['username'])
			if not user.check_password(self.cleaned_data['password']):
				self.add_error('password', 'La contraseña es incorrecta')


class UserCreateForm(forms.ModelForm):

	class Meta:
		model = User
		fields = ('username', 'password')
		widgets = {
			'username' : forms.TextInput(attrs={
					'type' : 'text',
					'placeholder' : 'Ingresa nombre de Usuario',
				}),
			'password' : forms.TextInput(attrs={
					'type' : 'password',
					'placeholder' : 'Ingrese una Contraseña',
				})
		} 

apps/invoices/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse, reverse_lazy


from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, DeleteView

from .models import Invoice
from .forms import InvoiceForm



class CreateInvoice(CreateView):

	form_class = InvoiceForm
	template_name = 'invoices/panel/crear.html'
	success_url = reverse_lazy('main:home')


class DetailInvoice(DetailView):

	template_name = 'invoices/panel/detalle.html'
	model = Invoice


class EditInvoice(UpdateView):

	template_name = 'invoices/panel/editar.html'
	success_url = reverse_lazy('main:home')
	model = Invoice
	form_class = InvoiceForm


class DeleteInvoice(DeleteView):

	template_name = 'invoices/panel/eliminar.html'
	model = Invoice
	success_url = reverse_lazy('main:home')
	context_object_name = 'invoice'

apps/main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from apps.invoices.models import Invoice

class Home(TemplateView):

	template_name="main/home.html"

	def get_context_data(self, **kwargs):
		context = super(Home, self).get_context_data(**kwargs)
		context['invoices'] = Invoice.objects.all()
		
		return context

apps/users/views.py
#encoding:utf-8
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, FormView, CreateView
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.auth import login, logout, authenticate
from .forms import UserLoginForm, UserCreateForm

def LogOut(request):
	logout(request)
	return redirect(reverse('main:home'))


class LoginView(FormView):

	template_name="users/login.html"
	form_class = UserLoginForm
	success_url = reverse_lazy('main:home')

	def form_valid(self, form):
		user = authenticate(
				username = form.cleaned_data['username'],
				password = form.cleaned_data['password'],
			)
		if user.is_active:
			login(self.request, user)
			return super(LoginView,self).form_valid(form)
		else:
			return redirect(reverse('users:register'))


class RegisterView(CreateView):

	template_name="users/register.html"
	form_class = UserCreateForm
	success_url = reverse_lazy('users:login')

	def form_valid(self, form):
		user = form.save()
		user.set_password(form.cleaned_data['password'])
		return super(RegisterView, self).form_valid(form)		

apps/invoices/templates/invoices/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>YORISlAB</title>
	{% load static from staticfiles %}
	<link rel="stylesheet" href="{% static 'css/fonts.css' %}">
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>
</head>
<body>
	<header class="cabecera">
		<div class="row row__space__between">
			<span class="logo"><a href="{% url 'main:home' %}">MIS FACTURAS</a></span>
			{% if user.is_authenticated %}			    
			    <ul class="menu">
					<li class="menu__item">Hola {{ user.username }}</li>
			    	<li class="menu__item"><a href="{% url 'users:logout' %}">Cerrar Sesión</a></li>	      
		    	</ul>
			{% else %}
				<ul class="menu">
			    	<li class="menu__item"><a href="{% url 'users:login' %}">Login</a></li>
			      	<li class="menu__item"><a href="{% url 'users:register' %}">Registrarse</a></li>
		    	</ul>		    			
			{% endif %}
		    
		</div>
    </header>

    {% block content %}
    {% endblock content %}

   	<footer class="footer">
    	<div class="contenedor">
        	<hr class="footer__linea">
        	<span class="footer__texto">Proyecto realizado por COA</span>
      	</div>
    </footer>

</body>
</html>

apps/invoices/templates/invoices/panel/crear.html
{% extends "base.html" %}

{% block content %}
    <div class="container">

        <div class="page-header">
            <h4>
                <a href="{% url 'main:home' %}" class="btn btn-success">
                    <span class="glyphicon glyphicon-chevron-left"></span> Regresar
                </a>
                <strong>Crear Factura</strong>
            </h4>
        </div><!-- page-header -->

        <div class="row">
            
            <div class="col-md-12">

                <form role="form" method="POST" enctype="multipart/form-data">{% csrf_token %}
                    <p class="lead"><span class="glyphicon glyphicon-info-sign"></span> Ingresa factura.</p>
                    {{ form.as_p }}
                     <button type="submit">Guardar</button>
                
                </form>

            </div><!-- col-md-12 -->

        </div><!-- /row -->

    </div><!-- /container -->

{% endblock content %}

apps/invoices/templates/invoices/panel/detalle.html
{% extends "base.html" %}

{% block content %}
    <div class="container">

        <div class="page-header">
            <h4>
                <a href="{% url 'main:home' %}" class="btn btn-success">
                    <span class="glyphicon glyphicon-chevron-left"></span> Regresar
                </a>
                <strong>Detalle Factura</strong>
            </h4>
        </div><!-- page-header -->

        <div class="row">            
            <div class="col-md-12">
              <section class="principal">
        <div class="contenedor">
            <h1 class="principal__titulo">Numero: {{ object.number }}</h1>
            <p class="principal__subtitulo">Fecha: {{ object.date }}</p>
            <p class="principal__subtitulo">Cliente: {{ object.cliente }}</p>
            <p class="principal__subtitulo">Total: {{ object.total }}</p>
        </div>
    </section>

            </div><!-- col-md-12 -->

        </div><!-- /row -->

    </div><!-- /container -->

{% endblock content %}

apps/invoices/templates/invoices/panel/editar.html
{% extends "base.html" %}

{% block content %}
    <div class="container">

        <div class="page-header">
            <h4>
                <a href="{% url 'main:home' %}" class="btn btn-success">
                    <span class="glyphicon glyphicon-chevron-left"></span> Regresar
                </a>
                <strong>Crear Factura</strong>
            </h4>
        </div><!-- page-header -->

        <div class="row">
            
            <div class="col-md-12">

                <form role="form" method="POST" enctype="multipart/form-data">{% csrf_token %}
                    <p class="lead"><span class="glyphicon glyphicon-info-sign"></span> Edita factura.</p>
                    {{ form.as_p }}
                     <button type="submit">Guardar</button>
                
                </form>

            </div><!-- col-md-12 -->

        </div><!-- /row -->

    </div><!-- /container -->

{% endblock content %}

apps/invoices/templates/invoices/panel/eliminar.html
{% extends "base.html" %}

{% block content %}
    <div class="container">

        <div class="page-header">
            <h4>
                <a href="{% url 'main:home' %}" class="btn btn-success">
                    <span class="glyphicon glyphicon-chevron-left"></span> Regresar
                </a>
                <strong>Eliminar Factura</strong>
            </h4>
        </div><!-- page-header -->

        <div class="row">
            
            <div class="col-md-12">

        <form role="form" action="{% url 'invoice_app:eliminar' invoice.id %}" method="POST">{% csrf_token %}
            <p class="">¿Desea eliminar la factura Numero:"{{ invoice.number }}"?</p>

            <input type="submit" value="Sí" class="btn btn-danger"> 
            <a href="{% url 'main:home' %}" class="btn btn-default">No</a>
        </form>

            </div><!-- col-md-12 -->

        </div><!-- /row -->

    </div><!-- /container -->

{% endblock content %}

apps/main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>YORISlAB</title>
	{% load static from staticfiles %}
	<link rel="stylesheet" href="{% static 'css/fonts.css' %}">
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

</head>
<body>
	<header class="cabecera">
		<div class="row row__space__between">
			<h3><a href="{% url 'main:home' %}">MIS FACTURAS</a></h3>
			{% if user.is_authenticated %}			    
			    <ul class="menu">
					<li class="menu__item">Hola {{ user.username }}</li>
			    	<li class="menu__item"><a href="{% url 'users:logout' %}">Cerrar Sesión</a></li>	      
		    	</ul>
			{% else %}
				<ul class="menu">
			    	<li class="menu__item"><a href="{% url 'users:login' %}">Login</a></li>
			      	<li class="menu__item"><a href="{% url 'users:register' %}">Registrarse</a></li>
		    	</ul>		    			
			{% endif %}
		    
		</div>
    </header>

    {% block content %}
    {% endblock content %}

   	<footer class="footer">
    	<div class="contenedor">
        	<hr class="footer__linea">
        	<span class="footer__texto">Proyecto realizado por COA</span>
      	</div>
    </footer>

</body>
</html>

apps/main/templates/main/home.html
{% extends "base.html" %}

{% block content %}
<section class="principal">
<div class="contenedor">
	<div class="row">

		<div class="col-md-12">

			<table class="table table-striped table-hover">
			<a class="btn btn-primary pull-left" href="{% url 'invoice_app:nuevo' %}">
				<span class="glyphicon glyphicon-plus"></span> Crear Factura
			</a>
				<thead>
					<tr>
						<th>Numero</th>
						<th>Cliente</th>
						<th>Fecha</th>
						<th>Total</th>						
						<th class="text-center">Acciones</th>
					</tr>
				</thead>
				<tbody>
					{% for invoice in invoices %}
					<tr>
						
						<td>{{ invoice.number }}</td>
						<td>{{ invoice.cliente }}</td>
						<td>{{ invoice.date }}</td>
						<td>{{ invoice.total }}</td>			
						<td  class="text-center">
							<a href="{% url 'invoice_app:detalle' invoice.id %}" class="btn btn-success"><span class="glyphicon glyphicon-eye-open"></span></a>
							<a href="{% url 'invoice_app:editar' invoice.id %}" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span></a>
							<a href="{% url 'invoice_app:eliminar' invoice.id %}" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a>
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>

		</div><!-- col-md-12 -->

	</div><!-- /row -->
</div>
</section>

{% endblock content %}

apps/users/templates/users/login.html
{% extends "base.html" %}

{% block content %}
	<div class="contenedor">

		<h2 class="login__registro">
			Log in
		</h2>
		<section class="login__registro__datos">
			<form method="POST">
				{% csrf_token %}
				<div class="login__registro__datos__ingresar">
					{{ form.username }}
					{{ form.username.errors }}
				</div>
				<div class="login__registro__datos__ingresar">
					{{ form.password }}
					{{ form.password.errors }}
				</div>
				<input type="submit" value="Ingresar" class="login__registro__datos__boton">
			</form>
		</section>
  	</div>
{% endblock content %}

apps/users/templates/users/register.html
{% extends "base.html" %}

{% block content %}
	<div class="contenedor">

		<h2 class="login__registro">
			Registro
		</h2>
		<section class="login__registro__datos">
			<form method="POST">
			{% csrf_token %}
				<div class="login__registro__datos__ingresar">					
					{{ form.username }}
					{{ form.username.errors }}
				</div>
				<div class="login__registro__datos__ingresar">
					{{ form.password }}
					{{ form.password.errors }}
				</div>
				<button type="submit" class="login__registro__datos__boton">Registrar</button>
			</form>
		</section>		
  	</div>
{% endblock content %}